theme: jekyll-theme-slate
title: Harry Booth's homepage
description: Hi, my name is Harry! I will use this page to showcase my projects, past and future. I am interested in applying systems thinking to the world, using computational methods. 
